// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               v3.21.12
// source: product.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "product";

export interface Response {
  code: number;
  status: string;
  timestamp: string;
  data: string;
  error: string;
}

export interface CreateProductRequest {
  name: string;
  category: string;
  subCategory?: string | undefined;
  gender?: string | undefined;
  brand: string;
  imageUrl: string;
  description: string;
  price: number;
  totalStock: number;
  variants: Variant[];
}

export interface UpdateProductRequest {
  id: string;
  name?: string | undefined;
  category?: string | undefined;
  subCategory?: string | undefined;
  gender?: string | undefined;
  brand?: string | undefined;
  imageUrl?: string | undefined;
  description?: string | undefined;
  price?: number | undefined;
  variants: Variant[];
}

export interface Variant {
  size: string;
  color: string;
  stock: number;
}

export interface ProductID {
  id: string;
}

export interface ProductFilter {
  page?: number | undefined;
  pageSize?: number | undefined;
  category?: string | undefined;
  brand?: string | undefined;
  subCategory?: string | undefined;
  name?: string | undefined;
  gender?: string | undefined;
}

export interface UpdateInventoryRequest {
  productId: string;
  variants: Variant[];
}

function createBaseResponse(): Response {
  return { code: 0, status: "", timestamp: "", data: "", error: "" };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.timestamp !== "") {
      writer.uint32(26).string(message.timestamp);
    }
    if (message.data !== "") {
      writer.uint32(34).string(message.data);
    }
    if (message.error !== "") {
      writer.uint32(42).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.code = object.code ?? 0;
    message.status = object.status ?? "";
    message.timestamp = object.timestamp ?? "";
    message.data = object.data ?? "";
    message.error = object.error ?? "";
    return message;
  },
};

function createBaseCreateProductRequest(): CreateProductRequest {
  return {
    name: "",
    category: "",
    subCategory: undefined,
    gender: undefined,
    brand: "",
    imageUrl: "",
    description: "",
    price: 0,
    totalStock: 0,
    variants: [],
  };
}

export const CreateProductRequest: MessageFns<CreateProductRequest> = {
  encode(message: CreateProductRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.category !== "") {
      writer.uint32(18).string(message.category);
    }
    if (message.subCategory !== undefined) {
      writer.uint32(26).string(message.subCategory);
    }
    if (message.gender !== undefined) {
      writer.uint32(34).string(message.gender);
    }
    if (message.brand !== "") {
      writer.uint32(42).string(message.brand);
    }
    if (message.imageUrl !== "") {
      writer.uint32(50).string(message.imageUrl);
    }
    if (message.description !== "") {
      writer.uint32(58).string(message.description);
    }
    if (message.price !== 0) {
      writer.uint32(65).double(message.price);
    }
    if (message.totalStock !== 0) {
      writer.uint32(72).int32(message.totalStock);
    }
    for (const v of message.variants) {
      Variant.encode(v!, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateProductRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProductRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subCategory = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.gender = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.brand = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.imageUrl = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.totalStock = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.variants.push(Variant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProductRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      subCategory: isSet(object.subCategory) ? globalThis.String(object.subCategory) : undefined,
      gender: isSet(object.gender) ? globalThis.String(object.gender) : undefined,
      brand: isSet(object.brand) ? globalThis.String(object.brand) : "",
      imageUrl: isSet(object.imageUrl) ? globalThis.String(object.imageUrl) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      totalStock: isSet(object.totalStock) ? globalThis.Number(object.totalStock) : 0,
      variants: globalThis.Array.isArray(object?.variants) ? object.variants.map((e: any) => Variant.fromJSON(e)) : [],
    };
  },

  toJSON(message: CreateProductRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.subCategory !== undefined) {
      obj.subCategory = message.subCategory;
    }
    if (message.gender !== undefined) {
      obj.gender = message.gender;
    }
    if (message.brand !== "") {
      obj.brand = message.brand;
    }
    if (message.imageUrl !== "") {
      obj.imageUrl = message.imageUrl;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    if (message.totalStock !== 0) {
      obj.totalStock = Math.round(message.totalStock);
    }
    if (message.variants?.length) {
      obj.variants = message.variants.map((e) => Variant.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<CreateProductRequest>): CreateProductRequest {
    return CreateProductRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateProductRequest>): CreateProductRequest {
    const message = createBaseCreateProductRequest();
    message.name = object.name ?? "";
    message.category = object.category ?? "";
    message.subCategory = object.subCategory ?? undefined;
    message.gender = object.gender ?? undefined;
    message.brand = object.brand ?? "";
    message.imageUrl = object.imageUrl ?? "";
    message.description = object.description ?? "";
    message.price = object.price ?? 0;
    message.totalStock = object.totalStock ?? 0;
    message.variants = object.variants?.map((e) => Variant.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpdateProductRequest(): UpdateProductRequest {
  return {
    id: "",
    name: undefined,
    category: undefined,
    subCategory: undefined,
    gender: undefined,
    brand: undefined,
    imageUrl: undefined,
    description: undefined,
    price: undefined,
    variants: [],
  };
}

export const UpdateProductRequest: MessageFns<UpdateProductRequest> = {
  encode(message: UpdateProductRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    if (message.category !== undefined) {
      writer.uint32(26).string(message.category);
    }
    if (message.subCategory !== undefined) {
      writer.uint32(34).string(message.subCategory);
    }
    if (message.gender !== undefined) {
      writer.uint32(42).string(message.gender);
    }
    if (message.brand !== undefined) {
      writer.uint32(50).string(message.brand);
    }
    if (message.imageUrl !== undefined) {
      writer.uint32(58).string(message.imageUrl);
    }
    if (message.description !== undefined) {
      writer.uint32(66).string(message.description);
    }
    if (message.price !== undefined) {
      writer.uint32(73).double(message.price);
    }
    for (const v of message.variants) {
      Variant.encode(v!, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateProductRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateProductRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.subCategory = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.gender = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.brand = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.imageUrl = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.variants.push(Variant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateProductRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      category: isSet(object.category) ? globalThis.String(object.category) : undefined,
      subCategory: isSet(object.subCategory) ? globalThis.String(object.subCategory) : undefined,
      gender: isSet(object.gender) ? globalThis.String(object.gender) : undefined,
      brand: isSet(object.brand) ? globalThis.String(object.brand) : undefined,
      imageUrl: isSet(object.imageUrl) ? globalThis.String(object.imageUrl) : undefined,
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      price: isSet(object.price) ? globalThis.Number(object.price) : undefined,
      variants: globalThis.Array.isArray(object?.variants) ? object.variants.map((e: any) => Variant.fromJSON(e)) : [],
    };
  },

  toJSON(message: UpdateProductRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.category !== undefined) {
      obj.category = message.category;
    }
    if (message.subCategory !== undefined) {
      obj.subCategory = message.subCategory;
    }
    if (message.gender !== undefined) {
      obj.gender = message.gender;
    }
    if (message.brand !== undefined) {
      obj.brand = message.brand;
    }
    if (message.imageUrl !== undefined) {
      obj.imageUrl = message.imageUrl;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.price !== undefined) {
      obj.price = message.price;
    }
    if (message.variants?.length) {
      obj.variants = message.variants.map((e) => Variant.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateProductRequest>): UpdateProductRequest {
    return UpdateProductRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateProductRequest>): UpdateProductRequest {
    const message = createBaseUpdateProductRequest();
    message.id = object.id ?? "";
    message.name = object.name ?? undefined;
    message.category = object.category ?? undefined;
    message.subCategory = object.subCategory ?? undefined;
    message.gender = object.gender ?? undefined;
    message.brand = object.brand ?? undefined;
    message.imageUrl = object.imageUrl ?? undefined;
    message.description = object.description ?? undefined;
    message.price = object.price ?? undefined;
    message.variants = object.variants?.map((e) => Variant.fromPartial(e)) || [];
    return message;
  },
};

function createBaseVariant(): Variant {
  return { size: "", color: "", stock: 0 };
}

export const Variant: MessageFns<Variant> = {
  encode(message: Variant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.size !== "") {
      writer.uint32(10).string(message.size);
    }
    if (message.color !== "") {
      writer.uint32(18).string(message.color);
    }
    if (message.stock !== 0) {
      writer.uint32(24).int32(message.stock);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Variant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.size = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.color = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.stock = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Variant {
    return {
      size: isSet(object.size) ? globalThis.String(object.size) : "",
      color: isSet(object.color) ? globalThis.String(object.color) : "",
      stock: isSet(object.stock) ? globalThis.Number(object.stock) : 0,
    };
  },

  toJSON(message: Variant): unknown {
    const obj: any = {};
    if (message.size !== "") {
      obj.size = message.size;
    }
    if (message.color !== "") {
      obj.color = message.color;
    }
    if (message.stock !== 0) {
      obj.stock = Math.round(message.stock);
    }
    return obj;
  },

  create(base?: DeepPartial<Variant>): Variant {
    return Variant.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Variant>): Variant {
    const message = createBaseVariant();
    message.size = object.size ?? "";
    message.color = object.color ?? "";
    message.stock = object.stock ?? 0;
    return message;
  },
};

function createBaseProductID(): ProductID {
  return { id: "" };
}

export const ProductID: MessageFns<ProductID> = {
  encode(message: ProductID, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductID {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductID {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: ProductID): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<ProductID>): ProductID {
    return ProductID.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProductID>): ProductID {
    const message = createBaseProductID();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseProductFilter(): ProductFilter {
  return {
    page: undefined,
    pageSize: undefined,
    category: undefined,
    brand: undefined,
    subCategory: undefined,
    name: undefined,
    gender: undefined,
  };
}

export const ProductFilter: MessageFns<ProductFilter> = {
  encode(message: ProductFilter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== undefined) {
      writer.uint32(8).int32(message.page);
    }
    if (message.pageSize !== undefined) {
      writer.uint32(16).int32(message.pageSize);
    }
    if (message.category !== undefined) {
      writer.uint32(26).string(message.category);
    }
    if (message.brand !== undefined) {
      writer.uint32(34).string(message.brand);
    }
    if (message.subCategory !== undefined) {
      writer.uint32(42).string(message.subCategory);
    }
    if (message.name !== undefined) {
      writer.uint32(50).string(message.name);
    }
    if (message.gender !== undefined) {
      writer.uint32(58).string(message.gender);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProductFilter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProductFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.brand = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.subCategory = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.gender = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProductFilter {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : undefined,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : undefined,
      category: isSet(object.category) ? globalThis.String(object.category) : undefined,
      brand: isSet(object.brand) ? globalThis.String(object.brand) : undefined,
      subCategory: isSet(object.subCategory) ? globalThis.String(object.subCategory) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      gender: isSet(object.gender) ? globalThis.String(object.gender) : undefined,
    };
  },

  toJSON(message: ProductFilter): unknown {
    const obj: any = {};
    if (message.page !== undefined) {
      obj.page = Math.round(message.page);
    }
    if (message.pageSize !== undefined) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.category !== undefined) {
      obj.category = message.category;
    }
    if (message.brand !== undefined) {
      obj.brand = message.brand;
    }
    if (message.subCategory !== undefined) {
      obj.subCategory = message.subCategory;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.gender !== undefined) {
      obj.gender = message.gender;
    }
    return obj;
  },

  create(base?: DeepPartial<ProductFilter>): ProductFilter {
    return ProductFilter.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ProductFilter>): ProductFilter {
    const message = createBaseProductFilter();
    message.page = object.page ?? undefined;
    message.pageSize = object.pageSize ?? undefined;
    message.category = object.category ?? undefined;
    message.brand = object.brand ?? undefined;
    message.subCategory = object.subCategory ?? undefined;
    message.name = object.name ?? undefined;
    message.gender = object.gender ?? undefined;
    return message;
  },
};

function createBaseUpdateInventoryRequest(): UpdateInventoryRequest {
  return { productId: "", variants: [] };
}

export const UpdateInventoryRequest: MessageFns<UpdateInventoryRequest> = {
  encode(message: UpdateInventoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    for (const v of message.variants) {
      Variant.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateInventoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateInventoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.variants.push(Variant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateInventoryRequest {
    return {
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      variants: globalThis.Array.isArray(object?.variants) ? object.variants.map((e: any) => Variant.fromJSON(e)) : [],
    };
  },

  toJSON(message: UpdateInventoryRequest): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.variants?.length) {
      obj.variants = message.variants.map((e) => Variant.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateInventoryRequest>): UpdateInventoryRequest {
    return UpdateInventoryRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateInventoryRequest>): UpdateInventoryRequest {
    const message = createBaseUpdateInventoryRequest();
    message.productId = object.productId ?? "";
    message.variants = object.variants?.map((e) => Variant.fromPartial(e)) || [];
    return message;
  },
};

export type ProductServiceService = typeof ProductServiceService;
export const ProductServiceService = {
  createProduct: {
    path: "/product.ProductService/CreateProduct",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateProductRequest): Buffer => Buffer.from(CreateProductRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateProductRequest => CreateProductRequest.decode(value),
    responseSerialize: (value: Response): Buffer => Buffer.from(Response.encode(value).finish()),
    responseDeserialize: (value: Buffer): Response => Response.decode(value),
  },
  updateProduct: {
    path: "/product.ProductService/UpdateProduct",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateProductRequest): Buffer => Buffer.from(UpdateProductRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateProductRequest => UpdateProductRequest.decode(value),
    responseSerialize: (value: Response): Buffer => Buffer.from(Response.encode(value).finish()),
    responseDeserialize: (value: Buffer): Response => Response.decode(value),
  },
  getProduct: {
    path: "/product.ProductService/GetProduct",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ProductID): Buffer => Buffer.from(ProductID.encode(value).finish()),
    requestDeserialize: (value: Buffer): ProductID => ProductID.decode(value),
    responseSerialize: (value: Response): Buffer => Buffer.from(Response.encode(value).finish()),
    responseDeserialize: (value: Buffer): Response => Response.decode(value),
  },
  listProducts: {
    path: "/product.ProductService/ListProducts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ProductFilter): Buffer => Buffer.from(ProductFilter.encode(value).finish()),
    requestDeserialize: (value: Buffer): ProductFilter => ProductFilter.decode(value),
    responseSerialize: (value: Response): Buffer => Buffer.from(Response.encode(value).finish()),
    responseDeserialize: (value: Buffer): Response => Response.decode(value),
  },
  deleteProduct: {
    path: "/product.ProductService/DeleteProduct",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ProductID): Buffer => Buffer.from(ProductID.encode(value).finish()),
    requestDeserialize: (value: Buffer): ProductID => ProductID.decode(value),
    responseSerialize: (value: Response): Buffer => Buffer.from(Response.encode(value).finish()),
    responseDeserialize: (value: Buffer): Response => Response.decode(value),
  },
  updateInventory: {
    path: "/product.ProductService/UpdateInventory",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateInventoryRequest): Buffer =>
      Buffer.from(UpdateInventoryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateInventoryRequest => UpdateInventoryRequest.decode(value),
    responseSerialize: (value: Response): Buffer => Buffer.from(Response.encode(value).finish()),
    responseDeserialize: (value: Buffer): Response => Response.decode(value),
  },
} as const;

export interface ProductServiceServer extends UntypedServiceImplementation {
  createProduct: handleUnaryCall<CreateProductRequest, Response>;
  updateProduct: handleUnaryCall<UpdateProductRequest, Response>;
  getProduct: handleUnaryCall<ProductID, Response>;
  listProducts: handleUnaryCall<ProductFilter, Response>;
  deleteProduct: handleUnaryCall<ProductID, Response>;
  updateInventory: handleUnaryCall<UpdateInventoryRequest, Response>;
}

export interface ProductServiceClient extends Client {
  createProduct(
    request: CreateProductRequest,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  createProduct(
    request: CreateProductRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  createProduct(
    request: CreateProductRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  updateProduct(
    request: UpdateProductRequest,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  updateProduct(
    request: UpdateProductRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  updateProduct(
    request: UpdateProductRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  getProduct(request: ProductID, callback: (error: ServiceError | null, response: Response) => void): ClientUnaryCall;
  getProduct(
    request: ProductID,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  getProduct(
    request: ProductID,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  listProducts(
    request: ProductFilter,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  listProducts(
    request: ProductFilter,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  listProducts(
    request: ProductFilter,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  deleteProduct(
    request: ProductID,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  deleteProduct(
    request: ProductID,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  deleteProduct(
    request: ProductID,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  updateInventory(
    request: UpdateInventoryRequest,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  updateInventory(
    request: UpdateInventoryRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
  updateInventory(
    request: UpdateInventoryRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Response) => void,
  ): ClientUnaryCall;
}

export const ProductServiceClient = makeGenericClientConstructor(
  ProductServiceService,
  "product.ProductService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ProductServiceClient;
  service: typeof ProductServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
